name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: "Build Windows"
    runs-on: windows-latest
    env:
      PARALLEL: -j 2

    steps:
      - uses: actions/checkout@v3

      # Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Cache external dependencies for glslang/SPIRV-Tools
      - name: Cache glslang / SPIRV-Tools
        id: cache-externals
        uses: actions/cache@v3
        with:
          path: external/*-build/output
          key: windows externals ${{ hashFiles('checkout_glslang_spirv_tools.sh', 'build_glslang_spirv_tools.sh') }}

      # Pull glslang / SPIRV-Tools if cache miss
      - name: Pull glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./checkout_glslang_spirv_tools.sh

      # Build glslang / SPIRV-Tools
      - name: Build glslang / SPIRV-Tools
        if: steps.cache-externals.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./build_glslang_spirv_tools.sh Release 4

      # Build SPIRV-Cross
      - name: Configure SPIRV-Cross
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DSPIRV_CROSS_WERROR=ON -DSPIRV_CROSS_MISC_WARNINGS=ON -DSPIRV_CROSS_SHARED=ON -DCMAKE_INSTALL_PREFIX=output -DCMAKE_BUILD_TYPE=Release -DSPIRV_CROSS_ENABLE_TESTS=ON

      - name: Build SPIRV-Cross
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake --build . --config Release --parallel 4
          cmake --build . --config Release --target install

      # Upload SPIRV-Cross binaries
      - uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: build/output

      # Run SPIRV-Cross tests
      - name: Test SPIRV-Cross
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: ctest --verbose -C Release

      # Build C++/CLI Project (SPIRVCrossWrapper)
      - name: Build C++/CLI Project
        run: |
          cd SPIRVCrossWrapper
          msbuild /p:Configuration=Release SPIRVCrossWrapper.vcxproj

      # Restore and Build .NET Solution
      - name: Restore and Build .NET Solution
        run: dotnet build USCSandbox.sln --configuration Release

      # Run .NET tests
      - name: Run .NET tests
        run: dotnet test USCSandbox.sln --verbosity normal

  reuse:
    name: "REUSE license check"
    runs-on: windows-latest
    container: khronosgroup/docker-images:asciidoctor-spec

    steps:
      - uses: actions/checkout@v3

      # REUSE license checker
      - name: license-check
        run: |
          reuse lint
