name: .NET Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Install dependencies including vcpkg and SPIRV-Cross
    - name: Install SPIRV-Cross via vcpkg
      shell: powershell
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install spirv-cross:x64-windows

    # Setup .NET 8
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build .NET project
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Copy SPIRV-Cross DLLs to output directory
    - name: Copy SPIRV-Cross DLLs
      shell: powershell
      run: |
        $outputDir = "bin\Release"
        New-Item -ItemType Directory -Path $outputDir -Force
        Copy-Item vcpkg\installed\x64-windows\bin\spirv-cross-c-shared.dll $outputDir

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
