name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          nuget-

    - name: Restore and Build .NET Solution
      run: dotnet build USCSandbox.sln

    # Install dependencies for building SPIRV-Cross
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++

    # Clone and build SPIRV-Cross
    - name: Clone SPIRV-Cross
      run: git clone --depth 1 https://github.com/KhronosGroup/SPIRV-Cross.git external/SPIRV-Cross

    - name: Build SPIRV-Cross
      run: |
        mkdir -p external/SPIRV-Cross/build
        cd external/SPIRV-Cross/build
        cmake -G Ninja ..
        ninja

    # Export SPIRV-Cross paths for .NET to use
    - name: Set up SPIRV-Cross paths
      run: |
        echo "SPIRV_CROSS_LIB=$(pwd)/external/SPIRV-Cross/build" >> $GITHUB_ENV
        echo "SPIRV_CROSS_INCLUDE=$(pwd)/external/SPIRV-Cross" >> $GITHUB_ENV

    # Run tests
    - name: Test .NET solution
      run: dotnet test USCSandbox.sln --verbosity normal
